[package]
name = "dotenvor"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.88"

[dependencies]

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "load"
harness = false
